"""Константы проекта."""

MAX_LENGTH_FOR_STR = 30

# User
USER = 'user'
ADMIN = 'admin'
LOCALIZED_USER = 'Пользователь'
LOCALIZED_ADMIN = 'Администратор'
ROLE_CHOICES = [
    (USER, LOCALIZED_USER),
    (ADMIN, LOCALIZED_ADMIN),
]
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_EMAIL_ADDRESS = 254

# Other
MAX_LENGTH_NAME = 256
MAX_LENGTH_SLUG = 50
MIN_COOKING_TIME = 1
MAX_SIZE_IMAGE = 1024*1024*5
