"""Константы проекта."""

MAX_LENGTH_FOR_STR = 30

# User
MAX_LENGTH_USERNAME = 150
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_EMAIL_ADDRESS = 254

# Other
MAX_LENGTH_NAME = 256
MAX_LENGTH_SLUG = 50
MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 1440
MIN_NUMBERS_OF_ELEMENTS = 1
MAX_NUMBERS_OF_ELEMENTS = 100
